CREATE table CON_EMPLEADOS(
EMP_ID NUMERIC(5,0)  in out NOT NULL,
EMP_NOMBRE VARCHAR2(50) NOT NULL,
EMP_APELLIDO VARCHAR2(50) NOT NULL,
EMP_CEDULA VARCHAR2(10)NOT NULL,
EMP_DIRECCION VARCHAR2(50) NOT NULL,
EMP_TELEFONO VARCHAR2(10) NOT NULL,
EMP_EMAIL VARCHAR2(30) NOT NULL,
EMP_GENERO VARCHAR2(20) NOT NULL,
EMP_ESTADO VARCHAR2(20)NOT NULL,
EMP_CONTRASENIA VARCHAR2(20) NOT NULL,
CARGOS_CAR_ID   NUMBER(5) NOT NULL

);

insert into CON_EMPLEADOS values(1,'Rolando',' Calle','0106137680','Cuenca','3051379','srctirado@gmail.com','Masculino','Soltero','rolando1',1);
COMMIT;
SELECT
    *
FROM CON_EMPLEADOS;
alter table con_empleados add CONSTRAINT EMP_ID_PK PRIMARY KEY(EMP_ID);--CLAVE PRIMARIA

CREATE table CON_CARGOS(
CAR_ID NUMERIC(5,0) NOT NULL,
CAR_NOMBRE VARCHAR2(50) NOT NULL
);

alter table con_cargos add CONSTRAINT CAR_ID_PK PRIMARY KEY(CAR_ID);
SELECT
    *
FROM CON_CARGOS;

drop table CON_EMPLEADOS;
insert into con_cargos values(1,'Secretario');
DESC CON_EMPLEADOS;
COMMIT;

