/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.vista.Facturacion;
import ec.edu.ups.vista.Categoria;
import ec.edu.ups.controlador.ConexionBD;
import ec.edu.ups.controlador.ControladorCargo;
import ec.edu.ups.controlador.ControladorEmpleado;
import static java.awt.Frame.MAXIMIZED_BOTH;



/**
 *
 * @author srcti
 */
public class Inicio1A extends javax.swing.JFrame {
    private VentanaEmpleado ventanaEmpleado;
    private VentanaCargo ventanaCargo;
    private ControladorEmpleado controladorEmpleado;
    private ControladorCargo controladorCargo;
    /**
     * Creates new form Inicio
     */
    private int empleado;
    private int n;
    
    public Inicio1A(int n,int empleado) {
        initComponents();
        controladorCargo = new ControladorCargo();
        controladorEmpleado = new ControladorEmpleado();
        this.empleado=empleado;
        this.n=n;
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveAsMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem1 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        helpMenu1 = new javax.swing.JMenu();
        contentMenuItem1 = new javax.swing.JMenuItem();
        contentMenuItem2 = new javax.swing.JMenuItem();
        contentMenuItem3 = new javax.swing.JMenuItem();
        editMenu1 = new javax.swing.JMenu();
        cutMenuItem1 = new javax.swing.JMenuItem();
        copyMenuItem1 = new javax.swing.JMenuItem();
        editMenu2 = new javax.swing.JMenu();
        cutMenuItem2 = new javax.swing.JMenuItem();
        copyMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Empleados");

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Cargo");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        saveAsMenuItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveAsMenuItemKeyPressed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        saveAsMenuItem1.setMnemonic('a');
        saveAsMenuItem1.setText("Administradores");
        saveAsMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem1ActionPerformed(evt);
            }
        });
        saveAsMenuItem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveAsMenuItem1KeyPressed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem1);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Proveedor");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Inicio");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        menuBar.add(helpMenu);

        helpMenu1.setMnemonic('h');
        helpMenu1.setText("Productos");

        contentMenuItem1.setMnemonic('c');
        contentMenuItem1.setText("Inicio");
        contentMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu1.add(contentMenuItem1);

        contentMenuItem2.setMnemonic('c');
        contentMenuItem2.setText("Categoria");
        contentMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu1.add(contentMenuItem2);

        contentMenuItem3.setMnemonic('c');
        contentMenuItem3.setText("Medida");
        contentMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu1.add(contentMenuItem3);

        menuBar.add(helpMenu1);

        editMenu1.setMnemonic('e');
        editMenu1.setText("Facturacion");

        cutMenuItem1.setMnemonic('t');
        cutMenuItem1.setText("Facturar");
        cutMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItem1ActionPerformed(evt);
            }
        });
        editMenu1.add(cutMenuItem1);

        copyMenuItem1.setMnemonic('y');
        copyMenuItem1.setText("Listar Facturacion");
        copyMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItem1ActionPerformed(evt);
            }
        });
        editMenu1.add(copyMenuItem1);

        menuBar.add(editMenu1);

        editMenu2.setMnemonic('e');
        editMenu2.setText("Configuracion");

        cutMenuItem2.setMnemonic('t');
        cutMenuItem2.setText("Licencias ");
        editMenu2.add(cutMenuItem2);

        copyMenuItem2.setMnemonic('y');
        copyMenuItem2.setText("Permisos");
        editMenu2.add(copyMenuItem2);

        menuBar.add(editMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:
        desktopPane.removeAll();
        desktopPane.repaint();
        ventanaCargo = new VentanaCargo(controladorCargo);
        desktopPane.add(ventanaCargo);
        ventanaCargo.show();
        
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        Proveedor proveedor= new Proveedor();
        desktopPane.add(proveedor);
        proveedor.show();
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void contentMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItem1ActionPerformed
        // TODO add your handling code here:
        Producto producto=new Producto();
        desktopPane.add(producto);
        producto.show();
    }//GEN-LAST:event_contentMenuItem1ActionPerformed

    private void cutMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItem1ActionPerformed
        // TODO add your handling code here:
        Facturacion facturacion=new Facturacion();
        desktopPane.add(facturacion);
        facturacion.show();    
    }//GEN-LAST:event_cutMenuItem1ActionPerformed

    private void copyMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyMenuItem1ActionPerformed

    private void contentMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItem2ActionPerformed
        // TODO add your handling code here:
        Categoria categoria =new Categoria();
        desktopPane.add(categoria);
        categoria.show();
    }//GEN-LAST:event_contentMenuItem2ActionPerformed

    private void contentMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItem3ActionPerformed
        // TODO add your handling code here:
        Medida medida=new Medida();
        desktopPane.add(medida);
        medida.show();
    }//GEN-LAST:event_contentMenuItem3ActionPerformed

    private void saveAsMenuItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveAsMenuItemKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_saveAsMenuItemKeyPressed

    private void saveAsMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem1ActionPerformed
        // TODO add your handling code here:
         desktopPane.removeAll();
        desktopPane.repaint();
        ventanaEmpleado = new VentanaEmpleado(controladorEmpleado,new ControladorCargo());
        ventanaEmpleado.setVisible(true);
        desktopPane.add(ventanaEmpleado);
        ventanaEmpleado.show();
    }//GEN-LAST:event_saveAsMenuItem1ActionPerformed

    private void saveAsMenuItem1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveAsMenuItem1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveAsMenuItem1KeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem contentMenuItem1;
    private javax.swing.JMenuItem contentMenuItem2;
    private javax.swing.JMenuItem contentMenuItem3;
    private javax.swing.JMenuItem copyMenuItem1;
    private javax.swing.JMenuItem copyMenuItem2;
    private javax.swing.JMenuItem cutMenuItem1;
    private javax.swing.JMenuItem cutMenuItem2;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu1;
    private javax.swing.JMenu editMenu2;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem1;
    // End of variables declaration//GEN-END:variables

}
