/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;


import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.modelo.Cliente;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author srcti
 */
public class VentanaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
  
    private ControladorCliente controladorCliente;
   
    private Cliente cliente;

    private int codigo;
    public VentanaCliente(ControladorCliente controladorCliente) {
        initComponents();
        this.controladorCliente= controladorCliente;
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genero = new javax.swing.ButtonGroup();
        Estado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rbtMasculino = new javax.swing.JRadioButton();
        rbtFemenino = new javax.swing.JRadioButton();
        rbtSoltero = new javax.swing.JRadioButton();
        rbtCasado = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbxBuscar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        bntGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Informacion Cliente")));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 41, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 35, 290, -1));

        jLabel2.setText("Apellido ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 64, -1, -1));

        jLabel3.setText("Cédula ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 92, -1, -1));

        jLabel5.setText("Direccion ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 120, -1, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 61, 290, -1));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 86, 290, -1));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 117, 290, -1));

        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 156, -1, -1));

        jLabel7.setText("Correo Electronico");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 182, -1, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 153, 210, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 179, 290, -1));

        jLabel8.setText("Genero");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 205, -1, -1));

        Genero.add(rbtMasculino);
        rbtMasculino.setText("Masculino");
        jPanel1.add(rbtMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 201, -1, -1));

        Genero.add(rbtFemenino);
        rbtFemenino.setText("Femenino");
        jPanel1.add(rbtFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 201, -1, -1));

        Estado.add(rbtSoltero);
        rbtSoltero.setText("Soltero");
        jPanel1.add(rbtSoltero, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 242, -1, -1));

        Estado.add(rbtCasado);
        rbtCasado.setText("Casado");
        jPanel1.add(rbtCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 242, -1, -1));

        jLabel10.setText("Estado");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 242, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Buscar por:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 22, -1, -1));

        cbxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja una Opcion", "Nombre", "Cedula" }));
        cbxBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBuscarActionPerformed(evt);
            }
        });
        jPanel5.add(cbxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 54, 130, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });
        jPanel5.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 92, 130, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 260, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 11, 930, 300));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 154, 110, -1));

        jLabel4.setText("Codigo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 59, -1, -1));

        txtCodigo.setEditable(false);
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 28, 72, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 195, 110, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        btnNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnNuevoKeyPressed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 120, 110, -1));

        bntGuardar.setText("Guardar");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(bntGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 91, 110, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 229, 110, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 180, 280));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 380, 330));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Cédula", "Direccion", "Telefono", "Correo", "Genero", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1280, 240));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 1310, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
      
        Cliente e = new Cliente();
        e.setCedula(txtCedula.getText());
        e.setNombre(txtNombre.getText());
        e.setApellido(txtApellido.getText());
        e.setEmail(txtEmail.getText());
        e.setDireccion(txtDireccion.getText());
        e.setTelefono(txtTelefono.getText());
        
        
        
        String genero;
        if(rbtFemenino.isSelected()){
           genero = "Femenino";
       }else{
           genero = "Masculino";
       }
        e.setGenero(genero);
         String estado;
        if(rbtSoltero.isSelected()){
           estado = "Soltero";
       }else{
           estado = "Casado";
       }
        
        e.setEstado(estado);
        e.setCodigo(codigo);
        controladorCliente.actualizar(e);
        
        if((String)cbxBuscar.getSelectedItem()=="Cedula"){
                buscarCedula();
            }else if((String)cbxBuscar.getSelectedItem()=="Nombre"){
                BuscarNombre();
            }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         controladorCliente.eliminar(codigo);
        if((String)cbxBuscar.getSelectedItem()=="Cedula"){
                buscarCedula();
            }else if((String)cbxBuscar.getSelectedItem()=="Nombre"){
                BuscarNombre();
            }
       
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
      //  System.out.println(0);
      dispose();
      
    }//GEN-LAST:event_btnSalirActionPerformed

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        // TODO add your handling code here:
        
        Cliente e = new Cliente();
        
        e.setNombre(txtNombre.getText());
        e.setApellido(txtApellido.getText());
        e.setCedula(txtCedula.getText());
        e.setDireccion(txtDireccion.getText());
        e.setTelefono(txtTelefono.getText());
        e.setEmail(txtEmail.getText());
         String genero;
        if(rbtFemenino.isSelected()){
           genero = "Femenino";
       }else{
           genero = "Masculino";
       }
        e.setGenero(genero); 
        String estado;
        if(rbtSoltero.isSelected()){
           estado = "Soltero";
       }else{
           estado = "Casado";
       }
        e.setEstado(estado);
        
        
        controladorCliente.crear(e);
    
    }//GEN-LAST:event_bntGuardarActionPerformed

    
    
    private void btnNuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnNuevoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoKeyPressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
       
        if(evt.getKeyCode()==10){
            if((String)cbxBuscar.getSelectedItem()=="Cedula"){
                buscarCedula();
            }  else if((String)cbxBuscar.getSelectedItem()=="Nombre"){
                BuscarNombre();
            }
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
         int seleccion =tblEmpleados.getSelectedRow();
        codigo=(int) tblEmpleados.getValueAt(seleccion, 0);
        txtNombre.setText(String.valueOf(tblEmpleados.getValueAt(seleccion, 1)));
        txtApellido.setText(String.valueOf(tblEmpleados.getValueAt(seleccion, 2)));
        txtCedula.setText(String.valueOf(tblEmpleados.getValueAt(seleccion, 3)));
        txtDireccion.setText(String.valueOf(tblEmpleados.getValueAt(seleccion, 4)));
        txtTelefono.setText(String.valueOf(tblEmpleados.getValueAt(seleccion, 5)));
        txtEmail.setText(String.valueOf(tblEmpleados.getValueAt(seleccion, 6)));
         if (tblEmpleados.getValueAt(seleccion, 7)=="Masculino"){
            rbtMasculino.setSelected(false);
            rbtFemenino.setSelected(true);
        }else{
            rbtMasculino.setSelected(true);
            rbtFemenino.setSelected(false);
        }
          if (tblEmpleados.getValueAt(seleccion, 8)=="Soltero"){
            rbtSoltero.setSelected(false);
            rbtCasado.setSelected(true);
        }else{
             rbtSoltero.setSelected(true);
            rbtCasado.setSelected(false);
        }
        
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void cbxBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed
    public void buscarCedula(){
        Cliente e=controladorCliente.buscarXCedula(txtBuscar.getText());
        DefaultTableModel modelo= (DefaultTableModel) tblEmpleados.getModel();
        modelo.setRowCount(0);
        if(e.getApellido()!= null){
       Object[] dato ={
           
           e.getCodigo(),
           e.getNombre(),
           e.getApellido(),
           e.getCedula(),
           e.getDireccion(),
           e.getTelefono(),
           e.getEmail(),
           e.getGenero(),
           e.getEstado(),
          
       };
       modelo.addRow(dato);
    }else{
            JOptionPane.showMessageDialog(this, "No existe el Cliente");
        }
    }
    
    public void BuscarNombre(){
        List<Cliente> lista=controladorCliente.buscarXNombre(txtBuscar.getText());
        DefaultTableModel modelo= (DefaultTableModel) tblEmpleados.getModel();
        modelo.setRowCount(0);
        if(lista.size()!=0){
        for (Cliente e : lista) {
           Object[] dato ={
           e.getCodigo(),
           e.getNombre(),
           e.getApellido(),
           e.getCedula(),
           e.getDireccion(),
           e.getTelefono(),
           e.getEmail(),
           e.getGenero(),
           e.getEstado(),
          };
           modelo.addRow(dato);
        }
        }else{
            JOptionPane.showMessageDialog(this, "Los Clientes no existen");
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Estado;
    private javax.swing.ButtonGroup Genero;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtCasado;
    private javax.swing.JRadioButton rbtFemenino;
    private javax.swing.JRadioButton rbtMasculino;
    private javax.swing.JRadioButton rbtSoltero;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public void limpiar() {
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
        txtDireccion.setText("");
        Genero.clearSelection();
        Estado.clearSelection();
       
    }




}
